### PR TITLE
Issue 2

### LINKED ISSUE #2: Handle exceptions instead of declaring them to be thrown
The line https://github.com/acmpesuecc/pinger/blob/master/src/main/java/pinger/Pinger.java#L11 declares that an `IOException` is thrown by the method. 

Instead of declaring it to be thrown, the entire method's contents should be wrapped in a `try {...} catch(...) {...}` statement to allow custom handling of the exception. The exception's stack trace should be printed along with some meaningful information about the exception.

### LINKED ISSUE #5: Append a new line after reading each line from the reader
After reading each line from the reader, a new line (`\n`) should be added to the string builder make the content easier to read. 
Specifically right after line 40. 
https://github.com/acmpesuecc/pinger/blob/8b164118db9035a5bd6fe8775164dbcfefa546e0/src/main/java/pinger/Pinger.java#L35-L41

### LINKED ISSUE #9: Allow running the program multiple times
At the end of the program, some input should be accepted to determine whether `main` should be called again. If the input matches something, `main` should be called again.

### PR DESCRIPTION
**Pull request by sreechand2002**
added new line char

### CODE REVIEW

File: src/main/java/pinger/Pinger.java [hunk 1]
```diff
@@ -8,25 +8,34 @@
...
+                        content = "No content returned";
+                    }
+                    addField("Content Type", conn.getContentType());
+                    addField("Request Method", conn.getRequestMethod());
+                    addField("Connection Timeout", conn.getConnectTimeout());
+                    addField("Response code", conn.getResponseCode());
+                    addField("Header Fields", conn.getHeaderFields());
+                    addField("Content", content);
+                    System.out.println("Enter y to continue and n to exit ");
+                    ch = (char) reader1.read();
```
Comment (BoogieMonster1O1) [inline src/main/java/pinger/Pinger.java]: use `reader1.readLine().charAt(0)`

**Review by sreechand2002 — COMMENTED** [review]
done

**Review by BoogieMonster1O1 — APPROVED** [review]

**Comment by Rishabkashyap14** [comment]
!bounty 30
